#!/bin/bash
echo "🎨 Daily Design Lab"
echo ""
echo "### Concept: THE SPINE (Vertical Integration)"
echo "**Theme:** Structural Support / Backbone"
echo "**Garment:** Heavyweight Oversized Tee (Charcoal/Black)."
echo "**Placement:** Vertical Center Back (Spine Line)."
echo "**Graphics:**"
echo "- **Text:** ALPHANIX [MMXXVI]"
echo "- **Orientation:** Vertical (Top to Bottom), running exactly down the spine."
echo "- **Font:** Bebas Neue (Bold, Condensed) or Druk Wide."
echo "- **Detail:** A thin, single line runs through the text, splitting the letters."
echo ""
echo "**Why it works:**"
echo "1. **Unique Placement:** Emphasizes back width and taper."
echo "2. **Lifting Alignment:** Aligns with bench/bar."
echo "3. **Minimal Front:** Blank chest, tiny hem tag."
